[package]
name = "ross-protocol"
version = "0.3.1"
authors = ["Linas NikiperaviÄius <linas@linasdev.com>"]
edition = "2018"

[dependencies]
bxcan = "^0.4.0"
nb = "^1.0.0"
embedded-hal = "^0.2.5"

[dependencies.cobs]
version = "^0.1.4"
default-features = false
